FROM alpine:3.14 AS build-stage
RUN apk --no-cache add go=1.16.15-r0
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
WORKDIR /app
COPY . .
ENV REQUEST_ORIGIN=https://example.com
RUN go version && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

FROM scratch
COPY --from=build-stage /app/server /
CMD ["./server"]
