version: '3'

services:
    backend:
        image: backend
        ports: 
            - 8080:8080
        environment:
            - REDIS_HOST=redis
    frontend:
        image: frontend
        ports: 
            - 5000:5000
    redis:
        image: redis:latest
        ports:
            - 6379:6379