FROM  node:16.20.2-bookworm
WORKDIR /usr/src/app
COPY . .
#check installation
RUN node -v
RUN npm -v
#install packages
RUN npm install
#build static files 
RUN npm run build
#install serve
RUN npm install -g serve
RUN useradd frontenduser
USER frontenduser
CMD ["serve", "-s", "-l", "5000", "build"]