version: '3.8'

services:
    backend:
        image: backend
        ports: 
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
    frontend:
        image: frontend
        ports: 
            - 5000:5000
    redis:
        image: redis:latest
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        container_name: possu
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./database:/var/lib/postgresql/data
