FROM  node:16.20.2-alpine3.18 as build-stage
WORKDIR /usr/src/app
COPY . .
RUN node -v && \
    npm -v  && \
    npm install && \
    npm run build

FROM  nginx:1.19-alpine
COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html

#original size 476.41 mb
#new size 23.79 mb
#docker run -p 5000:80 frontend