FROM  node:16.20.2-alpine3.18 as build-stage
WORKDIR /usr/src/app
COPY . .
RUN node -v && \
    npm -v  && \
    npm install && \
    npm run build

FROM  node:16.20.2-alpine3.18
COPY --from=build-stage /usr/src/app/build /build
RUN adduser -D frontenduser && \
    npm install -g serve
USER frontenduser
CMD ["serve", "-s", "-l", "5000", "build"]


#original size 476.41 mb
#new size 129.38 mb